# Generated by Django 3.0.6 on 2020-05-24 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateField(auto_created=True)),
                ('number', models.CharField(max_length=20)),
                ('status', model_utils.fields.StatusField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=100, no_check_for_status=True)),
                ('type', model_utils.fields.StatusField(choices=[('RATION_CARD', 'RATION_CARD'), ('NATIVITY', 'NATIVITY'), ('INCOME', 'INCOME'), ('IDENTITY', 'IDENTITY'), ('CAST', 'CAST'), ('TAX', 'TAX')], default='RATION_CARD', max_length=100, no_check_for_status=True)),
                ('panchayath', models.CharField(blank=True, max_length=120, null=True)),
                ('taluk', models.CharField(blank=True, max_length=120, null=True)),
                ('ward', models.CharField(blank=True, max_length=120, null=True)),
                ('house_name', models.CharField(blank=True, max_length=120, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=120, null=True)),
                ('card_holder_photo', models.ImageField(blank=True, null=True, upload_to='ration_card')),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('address', models.TextField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_0.RequestUser')),
            ],
        ),
    ]
