# Generated by Django 3.0.6 on 2020-05-24 12:11

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='villageofficer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='notificationservice',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='notificationservice',
            name='requested_on',
        ),
        migrations.RemoveField(
            model_name='notificationservice',
            name='status',
        ),
    ]
