# Generated by Django 3.0.6 on 2020-05-31 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageofficer',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_0.Village'),
        ),
    ]
