# Generated by Django 3.0.6 on 2020-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0002_auto_20200524_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='castservice',
            name='type',
            field=models.CharField(default='Cast', max_length=120),
        ),
        migrations.AddField(
            model_name='identityservice',
            name='type',
            field=models.CharField(default='Identity card', max_length=120),
        ),
        migrations.AddField(
            model_name='incomeservice',
            name='type',
            field=models.CharField(default='Income', max_length=120),
        ),
        migrations.AddField(
            model_name='nativityservice',
            name='type',
            field=models.CharField(default='Nativity', max_length=120),
        ),
        migrations.AddField(
            model_name='rationcardservice',
            name='type',
            field=models.CharField(default='Ration card', max_length=120),
        ),
        migrations.AddField(
            model_name='taxservice',
            name='type',
            field=models.CharField(default='Tax', max_length=120),
        ),
    ]
