# Generated by Django 3.0.6 on 2020-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0003_auto_20200524_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castservice',
            name='type',
            field=models.CharField(default='Caste', max_length=120),
        ),
    ]
